### ISSUE TITLE
missing dependency to libfftw3-dev

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_environment_perception#27]
this is not installed using `rosdep install`. please add to package.xml and add it to rosdep (if not listed already).

Built target topic_tools_generate_messages_lisp
/u/fmw/git/care-o-bot/src/cob_environment_perception/cob_3d_features/common/src/ShapeSPH/FST_semi_memo.cpp:81:19: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>

**Comment by ipa-rmb** [comment]
Fixed, pull request is pending.
