### ISSUE TITLE
fix message dependencies

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_environment_perception#29]
if building from scratch there seems to be some missconfigured message dependencies to 
`cob_object_perception_msgs` and `cob_3d_mapping_msgs`.

in `CMakeLists.txt` use 

```
add_dependencies(TARGET cob_object_perception_msgs_gencpp)
add_dependencies(TARGET cob_3d_mapping_msgs_gencpp)
```

where `TARGET` needs to be replaced by the package using the messages.

**Comment by ipa-rmb** [comment]
Please obey fxm's comment:

Also, when converting to package-format 2, we agreed to consequently use:
add_dependencies(TARGET ${${PROJECT_NAME}_EXPORTED_TARGETS}) in case you generate messages within this package and add_dependencies(TARGET ${catkin_EXPORTED_TARGETS}) in case this package includes any package that generates messages/services/actions....

(use add_dependencies(TARGET ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS}) in case both applies!)

Do not use any *_generate_messages_cpp or *_gen_cpp or alike.

**Comment by ipa-rmb** [comment]
should all be fixed by now.
