### ISSUE TITLE
substitute cob_srvs/Trigger with std_srvs/Trigger

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_environment_perception#32]
`Trigger` is now available in the `std_srvs` package and thus deleted from `cob_srvs`.
@ipa-josh: please substitute all instances in cob_environment_perception

**Comment by ipa-rmb** [comment]
Would PR #33 help with these problems? I cleaned up several packages of cob_environment_perception for indigo. Maybe it is not yet perfect (wrt. to lint) but much better than the current version.

**Comment by floweisshardt** [comment]
seems to be solved with #33
